name: push-test

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
  integration:
    name: integration
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check Out
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: integration test
        run: ./gradlew bootRun & ./gradlew localIntegration
